version: '3.9'

services:
  java_app:
    container_name: java_app
    image: abhishekblog/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/Blogapp
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=nasroot
    depends_on:
      - java_db
      
  java_db:
    container_name: java_db
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: nasroot
    volumes:
      - pgdata:/var/lib/mysql/data

volumes:
  pgdata: {}